import { Injectable } from '@angular/core';
import { Class } from 'src/app/interfaces/class';
import { Equipment } from 'src/app/interfaces/equipment';
import { Instructor } from 'src/app/interfaces/instructor';
import { MartialArt } from 'src/app/interfaces/martial-art';
// import { StudentIdEmail } from '../../interfaces/student-id-email'
import { IStudentSpring } from '../../interfaces/student-spring';
import { InMemoryDbService } from 'angular-in-memory-web-api';
// import { Student } from '../interfaces/student';

type TStudent = IStudentSpring;

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const equipments: Equipment[] = [
      {
        id: 1,
        name: 'Bo stick',
        price: 129.98,
      },
      {
        id: 2,
        name: 'Bokken',
        price: 22.0,
      },
      {
        id: 3,
        name: 'Hanbo',
        price: 16.9,
      },
      {
        id: 4,
        name: 'Katana',
        price: 169.0,
      },
      {
        id: 5,
        name: 'Tanto',
        price: 90.0,
      },
      {
        id: 6,
        name: 'Uniform',
        price: 117.5,
      },
      {
        id: 7,
        name: 'Uniform',
        price: 169.0,
      },
      {
        id: 8,
        name: 'Tan',
        price: 6,
      },
      {
        id: 9,
        name: 'to',
        price: 1,
      },
    ].sort((equipment) => equipment.id);

    const martialArts: MartialArt[] = [
      {
        id: 1,
        name: 'Aikido',
      },
      {
        id: 2,
        name: 'Baguazhang',
      },
      {
        id: 3,
        name: 'Boxing',
      },
      {
        id: 4,
        name: 'Brazilian JuJutsu',
      },
      {
        id: 5,
        name: 'JKD',
      },
      {
        id: 6,
        name: 'Judo',
      },
      {
        id: 7,
        name: 'Karate',
      },
      {
        id: 8,
        name: 'Kendo',
      },
      {
        id: 9,
        name: 'Kickboxing',
      },
      {
        id: 10,
        name: 'MMA',
      },
      {
        id: 11,
        name: 'Muay Thai',
      },
      {
        id: 12,
        name: 'Ninjutsu',
      },
      {
        id: 13,
        name: 'Shaolin Kung Fu',
      },
      {
        id: 14,
        name: 'Tai chi',
      },
      {
        id: 15,
        name: 'TKD',
      },
      {
        id: 16,
        name: 'Wing Chun',
      },
    ].sort((martialArt) => martialArt.id);

    const instructors: Instructor[] = [
      {
        id: 2004,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Astra',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2006,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Bell',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 1,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Bruce',
        lastName: 'Lee',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2005,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Heinz',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Ip',
        lastName: 'Man',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Jet',
        lastName: 'Li',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2002,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'May',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Mike',
        lastName: 'Tyson',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Muhammad',
        lastName: 'Ali',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 1001,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Nameless',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 1003,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'NoName',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2003,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Tzaho',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2001,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Xun',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2007,
        // username: 'chouki@fitworld.be',
        email: 'chouki@fitworld.be',
        password: 'chouki@2A',
        firstName: 'Yirusz',
        lastName: null,
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ].sort((instructor) => instructor.id);

    const classes: Class[] = [
      {
        id: 1,
        // martialArtId: 2,
        martialArt: martialArts[1],
        // instructorId: 1,
        instructor: instructors[0],
        dateTime: new Date('2023-02-06T11:31:00'),
        pricePerHour: 0.06,
      },
      {
        id: 2,
        // martialArtId: 16,
        martialArt: martialArts[15],
        // instructorId: 3,
        instructor: instructors[2],
        dateTime: new Date('2023-02-06T22:20:00'),
        pricePerHour: 0.42,
      },
      {
        id: 3,
        // martialArtId: 3,
        martialArt: martialArts[2],
        // instructorId: 4,
        instructor: instructors[3],
        dateTime: new Date('2023-02-06T22:21:00'),
        pricePerHour: 1.25,
      },
      {
        id: 4,
        // martialArtId: 3,
        martialArt: martialArts[2],
        // instructorId: 5,
        instructor: instructors[4],
        dateTime: new Date('2023-02-06T22:21:00'),
        pricePerHour: 1.17,
      },
      {
        id: 5,
        // martialArtId: 13,
        martialArt: martialArts[12],
        // instructorId: 2,
        instructor: instructors[1],
        dateTime: new Date('2023-02-06T22:22:00'),
        pricePerHour: 1.23,
      },
    ].sort((martialArtClass) => martialArtClass.id);

    // const students: StudentIdEmail[] = [
    const students: TStudent[] = [
      {
        id: 1,
        firstName: 'Andrew',
        lastName: 'Rix',
        email: 'andrew_rix@fitworld.be',
        // username: 'andrew_rix@fitworld.be',
        password: 'Andrew_rix@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        firstName: 'Bella',
        lastName: 'Novy',
        email: 'bella_novy@fitworld.be',
        // username: 'bella_novy@fitworld.be',
        password: 'bella_novy@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        firstName: 'Chris',
        lastName: 'Tyana',
        email: 'chris_tyana@fitworld.be',
        // username: 'chris_tyana@fitworld.be',
        password: 'chris_tyana@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        firstName: 'Danny',
        lastName: 'Kit',
        email: 'danny_kit@fitworld.be',
        // username: 'danny_kit@fitworld.be',
        password: 'danny_kit@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        firstName: 'Emma',
        lastName: 'Star',
        email: 'emma_star@fiworld.be',
        // username: 'emma_star@fitworld.be',
        password: 'emma_star@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        firstName: 'Fynn',
        lastName: 'Chin',
        email: 'fynn_chin@fitworld.be',
        // username: 'fynn_chin@fitworld.be',
        password: 'fynn_chin@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        firstName: 'Gottlieb',
        lastName: 'Master',
        email: 'gottlieb_master@fitworld.be',
        // username: 'gottlieb_master@fitworld.be',
        password: 'gottlieb_master@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        firstName: 'Hector',
        lastName: 'Sing',
        email: 'hector_sing@fitworld.be',
        // username: 'hector_sing@fitworld.be',
        password: 'hector_sing@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        firstName: 'Ibis',
        lastName: 'Fall',
        email: 'ibis_fall@fitworld.be',
        // username: 'ibis_fall@fitworld.be',
        password: 'ibis_fall@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        firstName: 'Jane',
        lastName: 'Red',
        email: 'jane_red@fitworld.be',
        // username: 'jane_red@fitworld.be',
        password: 'jane_red@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        firstName: 'Kourtney',
        lastName: 'K',
        email: 'kourtney_k@fitworld.be',
        // username: 'kourtney_k@fitworld.be',
        password: 'kourtney_k@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        firstName: 'Lore',
        lastName: 'Map',
        email: 'lore_map@fitworld.be',
        // username: 'lore_map@fitworld.be',
        password: 'lore_map@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        firstName: 'Mane',
        lastName: 'Shein',
        email: 'mane_shein@fitworld.be',
        // username: 'mane_shein@fitworld.be',
        password: 'mane_shein@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        firstName: 'Naave',
        lastName: 'Stem',
        email: 'naave_stem@fitworld.be',
        // username: 'naave_stem@fitworld.be',
        password: 'naave_stem@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        firstName: 'Olivia',
        lastName: 'Win',
        email: 'olivia_win@fitworld.be',
        // username: 'olivia_win@fitworld.be',
        password: 'olivia_win@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        firstName: 'Paolo',
        lastName: 'Rubia',
        email: 'paolo_rubia@fitworld.be',
        // username: 'paolo_rubia@fitworld.be',
        password: 'paolo_rubia@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        firstName: 'Qian',
        lastName: 'Storre',
        email: 'qian_storre@fitworld.be',
        // username: 'qian_storre@fitworld.be',
        password: 'qian_storre@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        firstName: 'Rider',
        lastName: 'Ban',
        email: 'rider_ban@fitworld.be',
        // username: 'rider_ban@fitworld.be',
        password: 'rider_ban@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        firstName: 'Shannon',
        lastName: 'Crow',
        email: 'shannon_crow@fitworld.be',
        // username: 'shannon_crow@fitworld.be',
        password: 'shannon_crow@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        firstName: 'Tiffany',
        lastName: 'Ruby',
        email: 'tiffany_ruby@fitworld.be',
        // username: 'tiffany_ruby@fitworld.be',
        password: 'tiffany_ruby@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        firstName: 'Ursula',
        lastName: 'Bear',
        email: 'ursula_bear@fitworld.be',
        // username: 'ursula_bear@fitworld.be',
        password: 'ursula_bear@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        firstName: 'Veronika',
        lastName: 'Bold',
        email: 'veronika_bold@fitworld.be',
        // username: 'veronika_bold@fitworld.be',
        password: 'veronika_bold@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        firstName: 'Walter',
        lastName: 'Must',
        email: 'walter_must@fitworld.be',
        // username: 'walter_must@fitworld.be',
        password: 'walter_must@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        firstName: 'Xena',
        lastName: 'Sim',
        email: 'xena_sim@fitworld.be',
        // username: 'xena_sim@fitworld.be',
        password: 'xena_sim@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        firstName: 'Yian',
        lastName: 'Exo',
        email: 'yian_exo@fitworld.be',
        // username: 'yian_exo@fitworld.be',
        password: 'yian_exo@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        firstName: 'Zen',
        lastName: 'Vann',
        email: 'zen_vann@fitworld.be',
        // username: 'zen_vann@fitworld.be',
        password: 'zen_vann@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        firstName: 'User',
        lastName: 'Name',
        email: 'username@site.tld',
        // username: 'username@fitworld.be',
        password: 'username@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        firstName: 'Masutatsu',
        lastName: 'Oyama',
        email: 'masutatsu@oyama.kr',
        // username: 'masutatsu@fitworld.be',
        password: 'masutatsu@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        firstName: 'Gichin',
        lastName: 'Funakoshi',
        email: 'gichin@funakoshi.jp',
        // username: 'gichin@fitworld.be',
        password: 'gichin@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        firstName: 'Anko',
        lastName: 'Itosu',
        email: 'anko@itosu.jp',
        // username: 'anko@fitworld.be',
        password: 'anko@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        firstName: 'Chouki',
        lastName: 'Motobu',
        email: 'chouki@motobu.jp',
        // username: 'chouki@fitworld.be',
        password: 'chouki@2A',
        ownedEquipments: [],
        classesTaken: [],
        authorities: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ].sort((student) => student.id);

    // TODO: discover reason why this must be encapsulated...!!
    // return students;
    return { students, equipments, martialArts, instructors, classes };
  }

  constructor() {}

  // genId<T extends StudentIdEmail | Equipment | MartialArt | Instructor | Class>(
  genId<T extends TStudent | Equipment | MartialArt | Instructor | Class>(
    collection: T[]
  ): number {
    console.log('typeof collection:', typeof collection);
    console.log('typeof (collection[0]):', typeof collection[0]);

    return collection.length > 0
      ? Math.max(...collection.map((member) => member.id)) + 1
      : 51;
  }
}
